// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGZj120GFq2S3GTLRP-zxjwirtCRQCdkg',
    appId: '1:1025155376064:web:e603d95a0f1d0eba0dde25',
    messagingSenderId: '1025155376064',
    projectId: 'proxy-killer-2356e',
    authDomain: 'proxy-killer-2356e.firebaseapp.com',
    databaseURL: 'https://proxy-killer-2356e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proxy-killer-2356e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByjxmFekfs3n5iZypzbqfuRXCX6LyEaLI',
    appId: '1:1025155376064:android:385e0e785c5840f20dde25',
    messagingSenderId: '1025155376064',
    projectId: 'proxy-killer-2356e',
    databaseURL: 'https://proxy-killer-2356e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proxy-killer-2356e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj28q4pHlgDkNBdueb7NfYRj_x7ANPJ0w',
    appId: '1:1025155376064:ios:96f29b5a1f26c9b70dde25',
    messagingSenderId: '1025155376064',
    projectId: 'proxy-killer-2356e',
    databaseURL: 'https://proxy-killer-2356e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proxy-killer-2356e.appspot.com',
    iosClientId: '1025155376064-j046e0it397re00ti0j4k7s4qjqar8gl.apps.googleusercontent.com',
    iosBundleId: 'com.example.proxyKiller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj28q4pHlgDkNBdueb7NfYRj_x7ANPJ0w',
    appId: '1:1025155376064:ios:96f29b5a1f26c9b70dde25',
    messagingSenderId: '1025155376064',
    projectId: 'proxy-killer-2356e',
    databaseURL: 'https://proxy-killer-2356e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proxy-killer-2356e.appspot.com',
    iosClientId: '1025155376064-j046e0it397re00ti0j4k7s4qjqar8gl.apps.googleusercontent.com',
    iosBundleId: 'com.example.proxyKiller',
  );
}
